export const ADD_TODO = 'ADD_TODO'
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
export const TOGGLE_TODO = 'TOGGLE_TODO'
<<<<<<< HEAD
export const REGISTER_SHOW_LOADING='REGISTER_SHOW_LOADING'
export const REGISTER_SHOW_REGISTER='REGISTER_SHOW_REGISTER'
export const SAVE_PERSON='SAVE_PERSON'
=======
export const MATCHER_SHOW_MATCHER="MATCHER_SHOW_MATCHER"
>>>>>>> 81088e7563c756cfa9fc35d5f15ae5280b5a642f
